branch-defaults:
  main:
    environment: tulipapp3-dev
    group_suffix: null
environment-defaults:
  tulipapp3-dev:
    branch: null
    repository: null
  tulipapp3-dev2:
    branch: null
    repository: null
global:
  application_name: tulipapp3
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
